### ISSUE TITLE
uninitialized constant LetterOpener::DeliveryMethod::Launchy

### ISSUE THREAD

**Issue by bengalamx** [ryanb/letter_opener#190]
I'm continually getting the error `uninitialized constant LetterOpener::DeliveryMethod::Launchy`.

Sometimes it works fine and suddenly I get that error, but is kind of a pain when you are trying to use email to end a ux.

**Comment by codemamba2080** [comment]
I have the same issue!! 

I even tried the last 6 versions of this gem and they seem to have the same issue.

Rails 5.2.6
Ruby 2.6.6

To get it to work, I need to restart my server every time, it's deathly annoying : (

**Comment by pedroceles** [comment]
I'm also getting that constantly. I need to restart rails server all the time.
Rails 5.2.6
Ruby 2.7.4

**Comment by nashby** [comment]
should be fixed by https://github.com/ryanb/letter_opener/commit/c67cc5b444b3b4ff394f81ee5b9756d0a766f311 @bengalamx @codemamba2080 @pedroceles could you please test master branch and report back?

**Comment by eaverdeja** [comment]
Hey @nashby! I'm getting a similar error using `1.8.1`: `NameError (uninitialized constant Launchy)`.

This happens at `lib/letter_opener/delivery_method.rb:25:in 'deliver!'`

Rails 5.2.7.1
Ruby 2.7.6

**Comment by miguelpeniche** [comment]
Hi @nashby, the `NameError` came back same as @eaverdeja described up here. Using `Rails 5.2.6` and `Ruby 2.7.2`

**Comment by nashby** [comment]
@miguelpeniche I'd love to investigate it if you could provide a sample app where I can reproduce your issue

**Comment by miguelpeniche** [comment]
Hey @nashby I am still having the same issues since then, I just accepted it and get used to it.

Just updated to `ruby 3.1.4` and `rails 6.1.7.3` and is still there. Just wanted to let you know.

<img width="1019" alt="screenshot 2023-06-04 a la(s) 13 24 09" src="https://github.com/ryanb/letter_opener/assets/3253845/2fdffa8c-423d-4b57-99e5-890e9539052d">

I can't provide a sample app as this is happening just in development in a fully working application in production.

**Comment by nashby** [comment]
hey @miguelpeniche. It's really hard to debug such issue and it makes it even harder to do without sample app that reproduces it, sorry. Could you please show your gemfile? Maybe it'll help somehow

**Comment by miguelpeniche** [comment]
Sure @nashby, my gemfile.lock file contains this 👇🏼

[gemfile.txt](https://github.com/ryanb/letter_opener/files/11780260/gemfile.txt)

**Comment by miguelpeniche** [comment]
Sure @nashby, I am attaching the content of my gemfile.lock and the logs of the error.

[gemfile.txt](https://github.com/ryanb/letter_opener/files/11780491/gemfile.txt)

[error_log.txt](https://github.com/ryanb/letter_opener/files/11780492/error_log.txt)

**Comment by miguelpeniche** [comment]
This error is persistent and have been here for a long time :(

**Comment by nashby** [comment]
@miguelpeniche have you tried latest version of `letter_opener`? I can see in your error_log that you're using `1.7.0`
